## YAML Template.
---
language: java
before_install:
    - cd ..
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/openvpms.git openvpms
    - cd $TRAVIS_BUILD_DIR
before_script:
    - cd ..
    - mysql -uroot < openvpms/src/test/resources/createdb.sql
    - mysql -e "CREATE DATABASE IF NOT EXISTS 'openvpms-1_8;" -uroot
    - mysql -e "GRANT ALL ON openvpms-1_8.* TO 'openvpms'@'localhost';" -uroot
    - cd $TRAVIS_BUILD_DIR
