## YAML Template.
---
language: java
before_install:
    - cd ..
    - git clone --branch=$TRAVIS_BRANCH git://github.com/CharltonIT/openvpms.git openvpms
    - cd Openvpms-framework
before_script:
    - cd ..
    - mysql -u root < openvpms/src/test/resources/createdb.sql
    - cd Openvpms-framework
